twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_4_horizontal_layout.html.twig']
    globals:
        eleicoesMapper: '@App\Mapper\EleicoesMapper'
        public_files_url: '/public_files'
